import type { PostTemplate, BrandKit, ColorPalette } from '@/types';

export const FONTS = [
  { name: 'Inter', value: 'Inter, sans-serif' },
  { name: 'Playfair Display', value: 'Playfair Display, serif' },
  { name: 'Montserrat', value: 'Montserrat, sans-serif' },
  { name: 'Roboto', value: 'Roboto, sans-serif' },
  { name: 'Open Sans', value: 'Open Sans, sans-serif' },
  { name: 'Poppins', value: 'Poppins, sans-serif' },
  { name: 'Lato', value: 'Lato, sans-serif' },
  { name: 'Oswald', value: 'Oswald, sans-serif' },
  { name: 'Raleway', value: 'Raleway, sans-serif' },
  { name: 'Bebas Neue', value: 'Bebas Neue, sans-serif' },
  { name: 'Space Grotesk', value: 'Space Grotesk, sans-serif' },
  { name: 'DM Sans', value: 'DM Sans, sans-serif' },
];

export const GRADIENTS = [
  { name: 'Ocean Blue', value: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
  { name: 'Sunset', value: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' },
  { name: 'Midnight', value: 'linear-gradient(135deg, #0c0c0c 0%, #1a1a2e 100%)' },
  { name: 'Forest', value: 'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)' },
  { name: 'Royal', value: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)' },
  { name: 'Coral', value: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)' },
  { name: 'Gold', value: 'linear-gradient(135deg, #f5af19 0%, #f12711 100%)' },
  { name: 'Aurora', value: 'linear-gradient(135deg, #00dbde 0%, #fc00ff 100%)' },
  { name: 'Coffee', value: 'linear-gradient(135deg, #4b3621 0%, #8b6914 100%)' },
  { name: 'Berry', value: 'linear-gradient(135deg, #8e2de2 0%, #4a00e0 100%)' },
  { name: 'Mint', value: 'linear-gradient(135deg, #00b09b 0%, #96c93d 100%)' },
  { name: 'Rose', value: 'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)' },
  { name: 'Deep Space', value: 'linear-gradient(135deg, #000000 0%, #434343 100%)' },
  { name: 'Peach', value: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)' },
  { name: 'Electric', value: 'linear-gradient(135deg, #00f260 0%, #0575e6 100%)' },
];

export const VIRAL_TEMPLATES: PostTemplate[] = [
  {
    id: 'inspirational-quote',
    name: 'İlham Veren Alıntı',
    category: 'viral',
    description: 'Motivasyonel alıntılar için premium tasarım',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    backgroundColor: '#1a1a2e',
    backgroundGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    elements: [
      {
        id: 'quote-text',
        type: 'text',
        content: '"Başarı,\nher gün\ntekrarlanan\nküçük çabaların\ntoplamıdır."',
        x: 50,
        y: 40,
        fontSize: 42,
        fontFamily: 'Playfair Display, serif',
        color: '#ffffff',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 1,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 1,
        textShadow: '2px 2px 4px rgba(0,0,0,0.5)',
      },
      {
        id: 'author-text',
        type: 'text',
        content: '— Robert Collier',
        x: 50,
        y: 75,
        fontSize: 18,
        fontFamily: 'Inter, sans-serif',
        color: '#e0e0e0',
        fontWeight: '400',
        textAlign: 'center',
        isBold: false,
        isItalic: true,
        isUnderline: false,
        letterSpacing: 2,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 0.9,
      },
    ],
    bestFor: ['Motivasyon', 'Kişisel gelişim', 'Liderlik'],
    engagementPrediction: 92,
  },
  {
    id: 'pro-tip',
    name: 'Pro İpucu Kartı',
    category: 'professional',
    description: 'Profesyonel ipuçları için dikkat çekici tasarım',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    backgroundColor: '#0f0f0f',
    backgroundGradient: 'linear-gradient(135deg, #0f0f0f 0%, #1a1a1a 100%)',
    elements: [
      {
        id: 'tip-badge',
        type: 'text',
        content: 'PRO TIP',
        x: 50,
        y: 15,
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        color: '#ffd700',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 4,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'tip-content',
        type: 'text',
        content: 'Toplantılarda\nnot almanın\nen etkili yolu:\n\nAnahtar kelimeler\nve kısa cümleler',
        x: 50,
        y: 50,
        fontSize: 36,
        fontFamily: 'Montserrat, sans-serif',
        color: '#ffffff',
        fontWeight: '600',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0.5,
        lineHeight: 1.5,
        rotation: 0,
        opacity: 1,
      },
    ],
    bestFor: ['İş ipuçları', 'Verimlilik', 'Kariyer'],
    engagementPrediction: 88,
  },
  {
    id: 'statistics-card',
    name: 'İstatistik Kartı',
    category: 'viral',
    description: 'Büyük sayılar ve etkileyici istatistikler',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'stat-number',
        type: 'text',
        content: '73%',
        x: 50,
        y: 35,
        fontSize: 120,
        fontFamily: 'Bebas Neue, sans-serif',
        color: '#2563eb',
        fontWeight: '400',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: -2,
        lineHeight: 1,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'stat-desc',
        type: 'text',
        content: 'çalışan, esnek çalışma\nsaatlerinin verimliliği\nartırdığını söylüyor',
        x: 50,
        y: 65,
        fontSize: 24,
        fontFamily: 'Inter, sans-serif',
        color: '#1f2937',
        fontWeight: '500',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 1,
      },
    ],
    bestFor: ['Araştırma', 'Veri görselleştirme', 'Raporlar'],
    engagementPrediction: 95,
  },
  {
    id: 'myth-fact',
    name: 'Myth vs Fact',
    category: 'trendy',
    description: 'Yaygın yanlış anlamaları düzeltin',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400',
    backgroundColor: '#fef3c7',
    elements: [
      {
        id: 'myth-label',
        type: 'text',
        content: 'MYTH',
        x: 25,
        y: 20,
        fontSize: 16,
        fontFamily: 'Inter, sans-serif',
        color: '#dc2626',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 3,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'myth-text',
        type: 'text',
        content: '"Uzaktan çalışmak\nverimsizdir"',
        x: 25,
        y: 40,
        fontSize: 22,
        fontFamily: 'Inter, sans-serif',
        color: '#7f1d1d',
        fontWeight: '500',
        textAlign: 'center',
        isBold: false,
        isItalic: true,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 0.8,
      },
      {
        id: 'fact-label',
        type: 'text',
        content: 'FACT',
        x: 75,
        y: 20,
        fontSize: 16,
        fontFamily: 'Inter, sans-serif',
        color: '#16a34a',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 3,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'fact-text',
        type: 'text',
        content: '"Uzaktan çalışanlar\n%47 daha verimli"',
        x: 75,
        y: 40,
        fontSize: 22,
        fontFamily: 'Inter, sans-serif',
        color: '#14532d',
        fontWeight: '600',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 1,
      },
    ],
    bestFor: ['Eğitim', 'Bilgilendirme', 'İçerik pazarlama'],
    engagementPrediction: 90,
  },
  {
    id: 'carousel-cover',
    name: 'Carousel Kapak',
    category: 'professional',
    description: 'Çoklu slayt gönderileri için kapak',
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400',
    backgroundColor: '#1e3a5f',
    backgroundGradient: 'linear-gradient(135deg, #1e3a5f 0%, #0d2137 100%)',
    elements: [
      {
        id: 'slide-number',
        type: 'text',
        content: '1/5',
        x: 90,
        y: 10,
        fontSize: 16,
        fontFamily: 'Inter, sans-serif',
        color: '#ffffff',
        fontWeight: '600',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 1,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 0.7,
      },
      {
        id: 'carousel-title',
        type: 'text',
        content: 'Stratejik\nPlanlama\nRehberi',
        x: 50,
        y: 45,
        fontSize: 48,
        fontFamily: 'Montserrat, sans-serif',
        color: '#ffffff',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 1,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'swipe-text',
        type: 'text',
        content: '→ Kaydırarak devam et',
        x: 50,
        y: 85,
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        color: '#94a3b8',
        fontWeight: '400',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 1,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 0.8,
      },
    ],
    bestFor: ['Eğitim serisi', 'Rehber', 'İçerik serisi'],
    engagementPrediction: 87,
  },
  {
    id: 'transformation',
    name: 'Dönüşüm Hikayesi',
    category: 'viral',
    description: 'Öncesi/sonrası formatı',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'before-label',
        type: 'text',
        content: 'BEFORE',
        x: 25,
        y: 15,
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        color: '#ef4444',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 3,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'before-text',
        type: 'text',
        content: 'Kaotik\nİş Süreçleri',
        x: 25,
        y: 40,
        fontSize: 28,
        fontFamily: 'Montserrat, sans-serif',
        color: '#fca5a5',
        fontWeight: '600',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.3,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'after-label',
        type: 'text',
        content: 'AFTER',
        x: 75,
        y: 15,
        fontSize: 14,
        fontFamily: 'Inter, sans-serif',
        color: '#22c55e',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 3,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'after-text',
        type: 'text',
        content: 'Optimize\nSistemler',
        x: 75,
        y: 40,
        fontSize: 28,
        fontFamily: 'Montserrat, sans-serif',
        color: '#86efac',
        fontWeight: '600',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.3,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'arrow',
        type: 'text',
        content: '→',
        x: 50,
        y: 35,
        fontSize: 48,
        fontFamily: 'Inter, sans-serif',
        color: '#fbbf24',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1,
        rotation: 0,
        opacity: 1,
      },
    ],
    bestFor: ['Vaka çalışması', 'Başarı hikayesi', 'Dönüşüm'],
    engagementPrediction: 93,
  },
  {
    id: 'checklist',
    name: 'Kontrol Listesi',
    category: 'professional',
    description: 'Etkileşimli kontrol listesi formatı',
    thumbnail: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400',
    backgroundColor: '#fefce8',
    elements: [
      {
        id: 'checklist-title',
        type: 'text',
        content: 'Haftalık\nKontrol Listesi',
        x: 50,
        y: 15,
        fontSize: 36,
        fontFamily: 'Montserrat, sans-serif',
        color: '#1f2937',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'item-1',
        type: 'text',
        content: '☑️ Öncelikleri belirle',
        x: 50,
        y: 45,
        fontSize: 20,
        fontFamily: 'Inter, sans-serif',
        color: '#374151',
        fontWeight: '500',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'item-2',
        type: 'text',
        content: '☑️ Takvimi gözden geçir',
        x: 50,
        y: 55,
        fontSize: 20,
        fontFamily: 'Inter, sans-serif',
        color: '#374151',
        fontWeight: '500',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'item-3',
        type: 'text',
        content: '☑️ Ekip toplantısı planla',
        x: 50,
        y: 65,
        fontSize: 20,
        fontFamily: 'Inter, sans-serif',
        color: '#374151',
        fontWeight: '500',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 0,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 1,
      },
    ],
    bestFor: ['Planlama', 'Üretkenlik', 'Ekip yönetimi'],
    engagementPrediction: 85,
  },
  {
    id: 'minimal-statement',
    name: 'Minimal Açıklama',
    category: 'minimal',
    description: 'Sade ve etkili mesaj',
    thumbnail: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?w=400',
    backgroundColor: '#fafafa',
    elements: [
      {
        id: 'statement',
        type: 'text',
        content: 'Az ama\nöz.',
        x: 50,
        y: 50,
        fontSize: 72,
        fontFamily: 'Space Grotesk, sans-serif',
        color: '#171717',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: -2,
        lineHeight: 1.1,
        rotation: 0,
        opacity: 1,
      },
    ],
    bestFor: ['Marka mesajı', 'Değer önerisi', 'Slogan'],
    engagementPrediction: 82,
  },
  {
    id: 'ai-future',
    name: 'AI Geleceği',
    category: 'trendy',
    description: 'Yapay zeka ve teknoloji teması',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400',
    backgroundColor: '#000000',
    backgroundGradient: 'linear-gradient(135deg, #000000 0%, #1a0a2e 50%, #16213e 100%)',
    elements: [
      {
        id: 'ai-badge',
        type: 'text',
        content: 'ARTIFICIAL INTELLIGENCE',
        x: 50,
        y: 15,
        fontSize: 12,
        fontFamily: 'Inter, sans-serif',
        color: '#a855f7',
        fontWeight: '600',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 4,
        lineHeight: 1.2,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'ai-title',
        type: 'text',
        content: 'Gelecek\nŞimdi',
        x: 50,
        y: 45,
        fontSize: 56,
        fontFamily: 'Space Grotesk, sans-serif',
        color: '#ffffff',
        fontWeight: '700',
        textAlign: 'center',
        isBold: true,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 2,
        lineHeight: 1.1,
        rotation: 0,
        opacity: 1,
        textShadow: '0 0 30px rgba(168, 85, 247, 0.5)',
      },
      {
        id: 'ai-subtitle',
        type: 'text',
        content: 'İş dünyasını dönüştüren teknoloji',
        x: 50,
        y: 75,
        fontSize: 16,
        fontFamily: 'Inter, sans-serif',
        color: '#c4b5fd',
        fontWeight: '400',
        textAlign: 'center',
        isBold: false,
        isItalic: false,
        isUnderline: false,
        letterSpacing: 1,
        lineHeight: 1.4,
        rotation: 0,
        opacity: 0.9,
      },
    ],
    bestFor: ['Teknoloji', 'İnovasyon', 'Gelecek trendleri'],
    engagementPrediction: 91,
  },
];

export const DEFAULT_BRAND_KITS: BrandKit[] = [
  {
    id: 'default',
    name: 'Varsayılan',
    primaryColor: '#2563eb',
    secondaryColor: '#1e40af',
    accentColor: '#f59e0b',
    fontHeading: 'Montserrat, sans-serif',
    fontBody: 'Inter, sans-serif',
  },
  {
    id: 'modern',
    name: 'Modern Kurumsal',
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    accentColor: '#06b6d4',
    fontHeading: 'Space Grotesk, sans-serif',
    fontBody: 'DM Sans, sans-serif',
  },
  {
    id: 'elegant',
    name: 'Zarif',
    primaryColor: '#881337',
    secondaryColor: '#be185d',
    accentColor: '#fbbf24',
    fontHeading: 'Playfair Display, serif',
    fontBody: 'Lato, sans-serif',
  },
  {
    id: 'bold',
    name: 'Cesur',
    primaryColor: '#dc2626',
    secondaryColor: '#991b1b',
    accentColor: '#fbbf24',
    fontHeading: 'Bebas Neue, sans-serif',
    fontBody: 'Roboto, sans-serif',
  },
];

export const COLOR_PALETTES: ColorPalette[] = [
  {
    name: 'Kurumsal Mavi',
    colors: ['#1e40af', '#3b82f6', '#60a5fa', '#93c5fd', '#dbeafe'],
    mood: 'Profesyonel, güvenilir',
  },
  {
    name: 'Enerjik Turuncu',
    colors: ['#c2410c', '#f97316', '#fb923c', '#fdba74', '#ffedd5'],
    mood: 'Enerjik, yaratıcı',
  },
  {
    name: 'Doğal Yeşil',
    colors: ['#166534', '#22c55e', '#4ade80', '#86efac', '#dcfce7'],
    mood: 'Doğal, sürdürülebilir',
  },
  {
    name: 'Lüks Mor',
    colors: ['#6b21a8', '#a855f7', '#c084fc', '#d8b4fe', '#f3e8ff'],
    mood: 'Lüks, yaratıcı',
  },
  {
    name: 'Minimal Gri',
    colors: ['#171717', '#404040', '#737373', '#a3a3a3', '#f5f5f5'],
    mood: 'Minimal, sofistike',
  },
  {
    name: 'Sıcak Kırmızı',
    colors: ['#991b1b', '#ef4444', '#f87171', '#fca5a5', '#fee2e2'],
    mood: 'Tutku, aciliyet',
  },
];

export const HASHTAG_CATEGORIES = {
  management: ['#leadership', '#management', '#business', '#strategy', '#consulting', '#executive', '#corporate'],
  consulting: ['#consulting', '#advisory', '#expertise', '#solutions', '#consultantlife', '#big4', '#strategyconsulting'],
  productivity: ['#productivity', '#efficiency', '#timemanagement', '#worksmarter', '#performance', '#optimization'],
  career: ['#career', '#professionaldevelopment', '#careergrowth', '#success', '#ambition', '#careeradvice'],
  innovation: ['#innovation', '#digitaltransformation', '#technology', '#futureofwork', '#disruption', '#ai'],
  motivation: ['#motivation', '#inspiration', '#mindset', '#successmindset', '#leadershipdevelopment', '#growthmindset'],
};

export const CONSULTING_QUOTES = [
  { text: 'Strateji, kaynakların doğru hedeflere yönlendirilmesidir.', author: 'Peter Drucker' },
  { text: 'Değişimi yönetenler başarılı olur, değişime direnenler kaybolur.', author: 'Jack Welch' },
  { text: 'Mükemmellik bir eylem değil, bir alışkanlıktır.', author: 'Aristotle' },
  { text: 'Liderlik, başkalarının görmediğini görmektir.', author: 'Sheryl Sandberg' },
  { text: 'Başarı, hazırlık ve fırsatın buluşmasıdır.', author: 'Bobby Unser' },
  { text: 'En iyi yatırım, kendine yapılan yatırımdır.', author: 'Warren Buffett' },
  { text: 'Veri, yeni petrolüdür. Ama işlenmemiş petrol değerlidir.', author: 'Clive Humby' },
  { text: 'İnovasyon, liderler ve takipçiler arasındaki farktır.', author: 'Steve Jobs' },
  { text: 'Müşteri deneyimi yeni savaş alanıdır.', author: 'Sundar Pichai' },
  { text: 'Agile olmak, hızlı olmak değil, esnek olmaktır.', author: 'Jeff Sutherland' },
];

export const VIRAL_HEADLINES = [
  '5 Strateji Hatası Şirketinizi Mahvediyor',
  'CEO\'ların Sabah 5\'te Yaptığı 3 Şey',
  'Bu Basit Değişiklik Verimliliğinizi %40 Artıracak',
  'Uzaktan Çalışmanın Gizli Maliyeti',
  '2025\'te Hayatta Kalacak Şirketlerin Özelliği',
  'Milyar Dolarlık Şirketlerin Ortak Özelliği',
  'Çalışanlarınızı Kaybetmenin Gerçek Maliyeti',
  'AI Çağında İşinizi Nasıl Korursunuz?',
  'Stratejik Planlama Yapmayan Şirketlerin Sonu',
  'Liderlik Tarzınızı Değiştirmenin Tam Zamanı',
];

export const ICONS_LIST = [
  'Target', 'TrendingUp', 'Users', 'Lightbulb', 'Rocket', 'Award', 'Star', 'Zap',
  'CheckCircle', 'AlertCircle', 'Info', 'BookOpen', 'Briefcase', 'Building2', 'Calendar',
  'ChartBar', 'ChartLine', 'ChartPie', 'Clock', 'Cog', 'Compass', 'CreditCard',
  'Database', 'FileText', 'Flag', 'Folder', 'Globe', 'Grid', 'Heart', 'Home',
  'Image', 'Inbox', 'Key', 'Layers', 'Link', 'Lock', 'Mail', 'Map', 'Menu',
  'MessageCircle', 'Monitor', 'Moon', 'Paperclip', 'Phone', 'Printer', 'Search',
  'Settings', 'Share2', 'Shield', 'ShoppingBag', 'Smartphone', 'Sun', 'Tablet',
  'Tag', 'ThumbsUp', 'Tool', 'Trash2', 'Upload', 'User', 'Video', 'Wifi',
];

export const SHAPES = [
  { type: 'rectangle', label: 'Dikdörtgen', icon: 'Square' },
  { type: 'circle', label: 'Daire', icon: 'Circle' },
  { type: 'triangle', label: 'Üçgen', icon: 'Triangle' },
  { type: 'star', label: 'Yıldız', icon: 'Star' },
  { type: 'line', label: 'Çizgi', icon: 'Minus' },
  { type: 'arrow', label: 'Ok', icon: 'ArrowRight' },
] as const;

export const IMAGE_FILTERS = [
  { name: 'Normal', value: 'none' },
  { name: 'Siyah-Beyaz', value: 'grayscale(100%)' },
  { name: 'Sepya', value: 'sepia(100%)' },
  { name: 'Yüksek Kontrast', value: 'contrast(150%)' },
  { name: 'Parlak', value: 'brightness(120%)' },
  { name: 'Sönük', value: 'brightness(80%)' },
  { name: 'Doygun', value: 'saturate(150%)' },
  { name: 'Soluk', value: 'saturate(50%)' },
  { name: 'Blurlu', value: 'blur(2px)' },
  { name: 'Vintage', value: 'sepia(50%) contrast(120%) saturate(80%)' },
  { name: 'HDR', value: 'contrast(130%) saturate(120%)' },
];

export const INSTAGRAM_SIZES = {
  square: { width: 1080, height: 1080, label: 'Kare (1:1)' },
  portrait: { width: 1080, height: 1350, label: 'Dikey (4:5)' },
  landscape: { width: 1080, height: 608, label: 'Yatay (16:9)' },
  story: { width: 1080, height: 1920, label: 'Hikaye (9:16)' },
  reel: { width: 1080, height: 1920, label: 'Reel (9:16)' },
};
